### ISSUE TITLE
Application can't be build on local

### ISSUE THREAD

**Issue by lehai2909** [aws-samples/react-cors-spa#16]
I try to run `npm install`, following by `yarn start` as the doc guide. But the app throw error, the installation process also throw a lot of warning about packet vulnerabilities. Have you guys test your app carefully before push it here?

**Comment by lehai2909** [comment]
![Screenshot 2024-05-28 at 14 05 49](https://github.com/aws-samples/react-cors-spa/assets/49013652/3a30e741-c3b7-4f78-8626-d16c0f19eb81)
![Screenshot 2024-05-28 at 14 06 31](https://github.com/aws-samples/react-cors-spa/assets/49013652/db2c0f05-d6d0-4279-a321-e620ff8a7add)

**Comment by SammyMasala** [comment]
@lehai2909 Having the same issue myself right now. This project is very outdated (last commit is over 1 year ago). React has had many changes over the last year. Biggest one for many boilerplate React apps is deprecation of create-react-app....

Project may not work anymore

**Comment by jeanbaptisteguillois** [comment]
These issues have now been fixed and the entire app has been updated to work with latest version of React (19) and Next (14).
